# Generated by Django 3.0.3 on 2020-02-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_auto_20200225_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
