# Generated by Django 3.0.3 on 2020-03-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0005_auto_20200308_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RecipeApp.Unit'),
        ),
    ]
