# Generated by Django 3.0.3 on 2020-03-08 17:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0006_auto_20200308_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
    ]
