# Generated by Django 3.0.3 on 2020-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0008_auto_20200308_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
